name: Checks

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['16.x']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          node_version: ${{ matrix.node_version }}

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['16.x']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          node_version: ${{ matrix.node_version }}

      - name: Build
        run: yarn nx affected:build

  lint:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['16.x']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          node_version: ${{ matrix.node_version }}

      - name: Lint
        run: yarn nx affected:lint

  test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['16.x']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          node_version: ${{ matrix.node_version }}

      - name: Test
        run: yarn nx affected:test

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          name: run-test-${{ matrix.node_version }}

  e2e:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['16.x']
        db_type: ['postgres', 'mysql']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          node_version: ${{ matrix.node_version }}

      - name: Run Docker Compose
        run: docker-compose -f ./examples/docker-compose.yml up -d

      - name: E2E
        run: yarn nx affected:e2e
        env:
          NESTJS_QUERY_DB_TYPE: ${{ matrix.db_type }}

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          name: run-e2e-${{ matrix.node_version }}
