name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          node_version: 16

      - name: Configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Build
        run: yarn nx run-many --target=build --projects=query-*

      - name: Release
        run: yarn nx version --configuration=release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
