name: Release documentation

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          node_version: 16

      - name: Build docs
        run: npx nx build documentation

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
